"use client"

import { useState, useEffect, useRef } from "react"
import type { PageId } from "../index"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import {
  ArrowLeft, Lock, CheckCircle2, XCircle, Loader2,
  Globe, X, TriangleAlert,
  FlaskConical, Copy, Check, RefreshCw, Info,
} from "lucide-react"
import type { BrandStatus } from "../index"

export type SimMode = "none" | "missing" | "rejected"

interface Props {
  navigate: (to: PageId) => void
  privacyPublished: boolean
  onPrivacyPublish: () => void
  brandStatus: BrandStatus
  showToast: (message: string) => void
  simMode: SimMode
  onSimModeChange: (mode: SimMode) => void
}

const PREFILLED_EIN = "98-7654321"
const maskedEin = `••-•••${PREFILLED_EIN.slice(-4)}`
const TODAY = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })

interface PolicyFields {
  companyName: string
  websiteUrl: string
  companyPhone: string
  contactEmail: string
  address: string
  repName: string
  messageFrequency: string
  retentionApplication: string
  retentionResident: string
  retentionComms: string
  retentionWebActivity: string
  retentionBackground: string
}

const DEFAULT_FIELDS: PolicyFields = {
  companyName: "Sunset Properties LLC",
  websiteUrl: "https://www.sunsetproperties.com",
  companyPhone: "(512) 555-0123",
  contactEmail: "sarah.johnson@sunsetproperties.com",
  address: "123 Main Street, Suite 200, Austin, TX 78701",
  repName: "Sarah Johnson",
  messageFrequency: "",
  retentionApplication: "",
  retentionResident: "",
  retentionComms: "",
  retentionWebActivity: "",
  retentionBackground: "",
}

const POLICY_TEMPLATE = (f: PolicyFields) => `PRIVACY POLICY
${f.companyName}
Effective Date: ${TODAY}
Last Updated: ${TODAY}

1. Introduction
This Privacy Policy describes how ${f.companyName} ("we," "us," or "our") collects, uses, discloses, and otherwise processes personal information in connection with our websites, mobile applications, text messaging and chatbot services, email communications, and the leasing, management, and operation of our residential apartment communities (collectively, the "Services"). This Privacy Policy applies to prospective residents, current residents, former residents, website visitors, and other individuals who interact with us through the Services.

2. Information We Collect
We collect the following categories of personal information:

A. Identifiers and Contact Information. Name, email address, phone number, mailing address, date of birth, and government-issued identification numbers (such as Social Security number, driver's license number, or passport number).
B. Financial and Payment Information. Bank account numbers, credit or debit card numbers, income and employment verification records, credit history and credit scores, and payment history.
C. Background Screening Information. Criminal background check results, eviction history, and credit reports obtained in connection with lease applications, subject to applicable law, including the Fair Credit Reporting Act.
D. Lease and Tenancy Information. Lease terms, unit number, move-in and move-out dates, rent payment records, maintenance request details, and other information related to your tenancy.
E. Communications Data. Transcripts and records of communications with us, including chatbot conversations, text messages, emails, and telephone call records.
F. Device and Online Activity Information. IP address, browser type and version, device identifiers, operating system, referring URLs, pages visited on our website, and similar tracking technologies.
G. Smart Home and IoT Device Data. Data generated by smart home devices installed in our communities, including smart lock access logs, thermostat usage, and connected device activity.
H. Inferences. Inferences drawn from the categories above to create a profile reflecting your preferences, characteristics, or behavior.
I. Sensitive Personal Information. Certain information we collect may be classified as sensitive under applicable state law, including Social Security numbers, government-issued identification numbers, financial account information, and background screening data.

3. Sources of Personal Information
We collect personal information:
• Directly from you, when you submit a lease application, sign a lease, make a payment, submit a maintenance request, or otherwise interact with us.
• From third-party service providers, including consumer reporting agencies, payment processors, and identity verification services.
• Automatically, through cookies and similar tracking technologies when you visit our website.
• From our technology platform providers, which operate our property management platform, chatbot, and text messaging services on our behalf.

4. How We Use Your Information
We use personal information for: leasing operations; rent collection and financial management; maintenance and property operations; resident communications; marketing and advertising (where permitted and where you have opted in); compliance with applicable laws; safety and security; and internal business operations and analytics.

5. How We Share Your Information
We share personal information with background screening providers, payment processors, maintenance vendors, insurance providers, smart lock and IoT providers, technology platform providers (including Entrata, which operates our property management platform), advertising networks, analytics providers, law enforcement and government entities, and professional advisors, as necessary for the purposes described above.

No mobile information will be shared with third parties or affiliates for marketing or promotional purposes.

6. Text Messaging, Chatbot, and Email Communications
By providing your phone number and consenting to receive text messages, you agree to receive transactional and, where you have separately opted in, promotional text messages from ${f.companyName} or our service providers, including through automated means.

Opt-in consent for text messaging is voluntary. You are not required to consent to text messaging as a condition of entering into a lease.

Opt-out. You may opt out of promotional text messages at any time by replying STOP to any message. For help, reply HELP or contact us at ${f.companyPhone} or ${f.contactEmail}.

Message frequency. ${f.messageFrequency === "varies" ? "Message frequency varies." : `You will receive approximately ${f.messageFrequency} messages per month.`} Message and data rates may apply. Carriers are not liable for delayed or undelivered messages.

No mobile information will be shared with third parties or affiliates for marketing or promotional purposes.

Our chatbot is operated by Entrata on our behalf. Communications through the chatbot are collected and processed in accordance with this Privacy Policy.

7. Cookies and Tracking Technologies
Our website uses cookies, web beacons, pixels, and similar tracking technologies. You may manage your cookie preferences through your browser settings. Disabling certain cookies may affect your ability to use some features of our website.

8. Your Privacy Rights
Depending on the state in which you reside, you may have rights to: know and access your personal information; correct inaccurate information; delete your personal information; data portability; opt out of sale or sharing; opt out of targeted advertising; opt out of profiling; limit use of sensitive personal information; and non-discrimination.

To exercise your rights, contact us at:
• Email: ${f.contactEmail}
• Mail: ${f.address}
• Phone: ${f.companyPhone}

We will respond to your request within the timeframe required by applicable law (generally 45 days). If we deny your request, you may appeal by contacting us at ${f.contactEmail}.

9. Data Security
We maintain reasonable administrative, technical, and physical safeguards to protect personal information, including encryption of data in transit and at rest, access controls, employee training, and periodic security assessments.

10. Children's Privacy
We do not knowingly collect personal information from individuals under the age of 16, and do not sell or share the personal information of individuals we know to be under 18.

11. Third-Party Links
Our website and communications may contain links to third-party websites. We are not responsible for the privacy practices of those third parties.

12. Changes to This Privacy Policy
We may update this Privacy Policy from time to time. Material changes will be posted on our website with a revised "Last Updated" date.

13. Contact Us
${f.companyName}
${f.address}
${f.companyPhone}
${f.contactEmail}
${f.websiteUrl}

14. State-Specific Supplements

14.1 California Residents (CCPA/CPRA)
Data retention periods:
• Lease application data (non-residents): ${f.retentionApplication} years from date of application.
• Resident data: Duration of lease plus ${f.retentionResident} years following lease termination.
• Communications records (texts, chatbot, email): ${f.retentionComms} years.
• Website activity data (cookies, analytics): ${f.retentionWebActivity} months.
• Background screening reports: ${f.retentionBackground} years, subject to FCRA requirements.

We do not offer financial incentive programs related to the collection of personal information.
To opt out of the sale or sharing of personal information, contact us at ${f.contactEmail}.

14.2 Minnesota Residents
Privacy Officer: ${f.repName}, ${f.contactEmail}, ${f.companyPhone}.

14.3 Maryland Residents
We do not sell sensitive personal information of Maryland residents and do not use geofencing technology near health care facilities.

14.4 Colorado, Oregon, and Connecticut Residents
We honor universal opt-out mechanisms, including the Global Privacy Control. We will obtain your consent before processing sensitive personal information where required by applicable law.

14.5 Virginia, Texas, Delaware, Montana, New Hampshire, New Jersey, Nebraska, Iowa, Tennessee, Indiana, Kentucky, Rhode Island, Utah, and Florida Residents
Residents of these states have the rights described in Section 8, subject to each state's specific scope and limitations. For questions, contact our Privacy Officer at ${f.contactEmail}.`.trim()

type RejectedField = "legal" | "ein" | "address" | "phone" | "website" | "rep-name" | "rep-email" | "rep-phone"

const CARRIER_REJECTION_MESSAGES: Record<RejectedField, string> = {
  "legal":     "Your business name couldn't be matched against official registration records. Update it to exactly match your state or federal business registration.",
  "ein":       "Your Federal Tax ID couldn't be verified against IRS records. Make sure it matches your official registration exactly (format: XX-XXXXXXX).",
  "address":   "Your business address wasn't recognized. Make sure it matches your state registration and is formatted as a standard mailing address.",
  "phone":     "This number couldn't be verified as a business line. Use a direct business phone — not a forwarding or virtual number.",
  "website":   "Your website URL couldn't be verified. Make sure it's publicly accessible and belongs to your registered business.",
  "rep-name":  "The authorized representative name doesn't match registration records. Use the full legal name of someone authorized to act for the company.",
  "rep-email": "This email couldn't be verified as associated with your business domain.",
  "rep-phone": "The representative phone number couldn't be verified. Use a direct business or personal number.",
}

const MISSING_MESSAGES: Record<RejectedField, string> = {
  "legal":     "Please provide your legal business name.",
  "ein":       "Your Federal Tax ID is required for carrier registration.",
  "address":   "Please provide your complete business address.",
  "phone":     "Please provide a company phone number.",
  "website":   "Please provide your business website URL.",
  "rep-name":  "Please provide the authorized representative's full name.",
  "rep-email": "Please provide the authorized representative's email address.",
  "rep-phone": "Please provide the authorized representative's phone number.",
}

// ── Small reusable components ────────────────────────────────────────────────

function RequiredLabel({ children }: { children: React.ReactNode }) {
  return (
    <label className="block text-sm font-semibold text-foreground mb-1.5">
      <span className="text-red-500 mr-1">*</span>{children}
    </label>
  )
}

interface FieldInfoData { what: string; why: string; tip?: string }

function FieldInfo({ data }: { data: FieldInfoData }) {
  const [open, setOpen] = useState(false)
  const [openUp, setOpenUp] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  function handleEnter() {
    if (ref.current) {
      const rect = ref.current.getBoundingClientRect()
      // If less than 280px below the icon, open upward
      setOpenUp(window.innerHeight - rect.bottom < 280)
    }
    setOpen(true)
  }

  return (
    <div
      ref={ref}
      className="relative inline-flex items-center ml-1.5 cursor-default align-middle"
      onMouseEnter={handleEnter}
      onMouseLeave={() => setOpen(false)}
    >
      <Info className="h-3.5 w-3.5 text-zinc-400 hover:text-zinc-600 transition-colors" />
      {open && (
        <div className={cn(
          "pointer-events-none absolute left-full ml-2 w-72 rounded-xl border border-zinc-200 bg-white shadow-xl z-50 overflow-hidden",
          openUp ? "bottom-0" : "top-0",
        )}>
          <div className="px-4 py-3 space-y-2.5">
            <div>
              <p className="text-[10px] font-bold text-zinc-500 uppercase tracking-wide mb-0.5">What it is</p>
              <p className="text-xs text-zinc-700 leading-relaxed">{data.what}</p>
            </div>
            <div className="border-t border-zinc-100 pt-2.5">
              <p className="text-[10px] font-bold text-zinc-500 uppercase tracking-wide mb-0.5">Why it matters</p>
              <p className="text-xs text-zinc-700 leading-relaxed">{data.why}</p>
            </div>
            {data.tip && (
              <div className="border-t border-zinc-100 pt-2.5">
                <p className="text-xs text-blue-700 leading-relaxed bg-blue-50 rounded-md px-2.5 py-1.5">{data.tip}</p>
              </div>
            )}
          </div>
          {/* Arrow pointing left, positioned to match the icon */}
          <div className={cn(
            "absolute right-full w-0 h-0 border-t-4 border-b-4 border-r-4 border-t-transparent border-b-transparent border-r-zinc-200",
            openUp ? "bottom-3" : "top-3",
          )} />
        </div>
      )}
    </div>
  )
}

function LabelWithInfo({ children, info }: { children: React.ReactNode; info: FieldInfoData }) {
  return (
    <div className="flex items-center mb-1.5">
      <label className="text-sm font-semibold text-foreground">
        <span className="text-red-500 mr-1">*</span>{children}
      </label>
      <FieldInfo data={info} />
    </div>
  )
}

// ── Field-level guidance (sourced from Twilio A2P 10DLC docs) ─────────────────
const FIELD_INFO = {
  legal: {
    what: "The exact name registered with your state or the IRS — not a DBA, trade name, or abbreviation.",
    why: "Carriers verify against federal and state records. Even minor differences in spelling or structure (e.g. 'LLC' vs 'L.L.C.') will cause rejection.",
    tip: "Check your IRS EIN confirmation letter or state filing certificate for the exact format.",
  },
  ein: {
    what: "Your IRS-issued 9-digit Employer Identification Number, formatted as XX-XXXXXXX.",
    why: "Required for Standard brand registration and must match your IRS filing exactly. Businesses with an EIN cannot register as a Sole Proprietor.",
    tip: "Found on your IRS EIN assignment letter (CP-575) or any federal tax filing.",
  },
  address: {
    what: "The physical address on file with your state business registration.",
    why: "Carriers cross-reference against state records. P.O. boxes, virtual offices, and addresses that differ from your state filing are rejected.",
    tip: "Use the address from your state filing or EIN application — not necessarily your current mailing address.",
  },
  phone: {
    what: "A direct, verifiable business line — not a forwarding, VoIP, or virtual number.",
    why: "Carriers confirm this is an active, real business number. Forwarding and virtual lines are frequently flagged and rejected.",
    tip: "Use a landline or direct business mobile associated with your company, not a receptionist relay.",
  },
  website: {
    what: "Your publicly accessible business website — must match your registered business name.",
    why: "Carriers visit your site to verify it's live and belongs to your registered business. Password-protected, under-construction, or mismatched URLs cause rejection.",
    tip: "If your site is unavailable, a public LinkedIn company page can be used as a substitute.",
  },
  privacy: {
    what: "A public page describing how you collect, use, and protect consumer data.",
    why: "Required by all carriers. Must explicitly state that mobile data will never be sold or shared with third parties — missing this language is a top rejection cause.",
    tip: "Make sure the page is publicly accessible (not behind a login or set to draft) before submitting.",
  },
  repName: {
    what: "The full legal name of a person authorized to legally act on behalf of the company.",
    why: "Used for identity verification against business records. Nicknames, initials, or names without signing authority will be rejected.",
    tip: "This person assumes legal responsibility for messaging compliance. Use the name as it appears on official company documents.",
  },
  repEmail: {
    what: "An email at your registered business domain (e.g. name@yourcompany.com).",
    why: "Carriers verify the email domain matches your registered website. Gmail, Yahoo, or personal email addresses significantly increase rejection risk.",
  },
  repPhone: {
    what: "A direct phone number for the authorized representative.",
    why: "Used for identity verification. VoIP and forwarding numbers may cause issues — use a direct mobile or business line.",
  },
} satisfies Record<string, FieldInfoData>

function Field({ children, className }: { children: React.ReactNode; className?: string }) {
  return <div className={cn("space-y-0", className)}>{children}</div>
}

function InlineError({ message }: { message: string }) {
  return (
    <p className="mt-1.5 flex items-center gap-1.5 text-xs text-red-600">
      <TriangleAlert className="h-3.5 w-3.5 shrink-0" />
      {message}
    </p>
  )
}

function CarrierRejectionCard({ reason, onDismiss }: { reason: string; onDismiss: () => void }) {
  return (
    <div className="mt-2 rounded-lg border border-red-200 bg-red-50 px-4 py-3 space-y-3">
      <div className="flex items-start gap-2.5">
        <XCircle className="h-4 w-4 text-red-500 mt-0.5 shrink-0" />
        <div>
          <p className="text-sm font-medium text-red-900">Not recognized by our carrier</p>
          <p className="text-xs text-red-700 mt-1 leading-relaxed">{reason}</p>
        </div>
      </div>
      <div className="border-t border-red-200 pt-2.5 flex justify-end">
        <button type="button" onClick={onDismiss}
          className="text-xs font-medium text-red-700 hover:text-red-900 transition-colors"
        >
          I've updated this →
        </button>
      </div>
    </div>
  )
}

// ── Retention periods accordion (optional, collapsed by default) ─────────────

function RetentionAccordion({
  fields,
  setField,
}: {
  fields: PolicyFields
  setField: (key: keyof PolicyFields, val: string) => void
}) {
  const retentionRows: { label: string; key: keyof PolicyFields; unit: string; hint: string }[] = [
    { label: "Lease application data (non-residents)", key: "retentionApplication", unit: "yrs", hint: "Common: 5 yrs" },
    { label: "Resident data after lease ends", key: "retentionResident", unit: "yrs", hint: "Common: 7 yrs" },
    { label: "Communications (texts, email, chat)", key: "retentionComms", unit: "yrs", hint: "Common: 3 yrs" },
    { label: "Website activity & cookies", key: "retentionWebActivity", unit: "mo", hint: "Common: 24 mo" },
    { label: "Background screening reports", key: "retentionBackground", unit: "yrs", hint: "FCRA min: 7 yrs" },
  ]
  const allFilled = retentionRows.every(r => fields[r.key] !== "")
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <label className="text-[11px] font-semibold text-amber-900">
          <span className="text-red-500 mr-1">*</span>Data retention periods
        </label>
        {!allFilled && (
          <span className="text-[10px] text-red-600 flex items-center gap-1">
            <TriangleAlert className="h-3 w-3" /> All fields required
          </span>
        )}
      </div>
      <p className="text-[11px] text-amber-700">How long you keep each type of data. Your legal team should confirm these. Common industry values are shown as a guide.</p>
      <div className="rounded-lg border border-amber-200 bg-white divide-y divide-amber-100">
        {retentionRows.map(({ label, key, unit, hint }) => (
          <div key={key} className="flex items-center gap-3 px-4 py-2.5">
            <span className="text-[11px] text-zinc-700 flex-1 leading-snug">{label}</span>
            <div className="flex items-center gap-1.5 shrink-0">
              <input
                type="number"
                min={1}
                value={fields[key]}
                placeholder="—"
                onChange={(e) => setField(key, e.target.value)}
                className={cn(
                  "w-14 h-7 rounded-md border px-2 text-xs text-center focus:outline-none focus:ring-2 focus:ring-amber-400/30 bg-white",
                  fields[key] === "" ? "border-amber-300 placeholder:text-amber-300" : "border-amber-200 text-foreground",
                )}
              />
              <span className="text-[11px] text-zinc-500">{unit}</span>
            </div>
            <span className="text-[10px] text-zinc-400 shrink-0 w-24 text-right">{hint}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Privacy Policy section — self-contained ──────────────────────────────────

function PrivacyPolicySection({
  websiteUrl,
  privacyPublished,
  onPrivacyPublish,
  simPrivacyRejected,
  onSimPrivacyDismiss,
  showMissingError,
  showToast,
}: {
  websiteUrl: string
  privacyPublished: boolean
  onPrivacyPublish: () => void
  simPrivacyRejected: boolean
  onSimPrivacyDismiss: () => void
  showMissingError: boolean
  showToast?: (msg: string) => void
}) {
  const [privacyFaded, setPrivacyFaded] = useState(false)
  const [fields, setFields] = useState<PolicyFields>(DEFAULT_FIELDS)
  const [copied, setCopied] = useState(false)
  const [awaitingConfirm, setAwaitingConfirm] = useState(false)
  const [verifying, setVerifying] = useState(false)

  const retentionKeys: (keyof PolicyFields)[] = [
    "retentionApplication", "retentionResident", "retentionComms",
    "retentionWebActivity", "retentionBackground",
  ]
  const policyReady =
    fields.messageFrequency !== "" &&
    retentionKeys.every((k) => fields[k] !== "")
  const [disclaimerOpen, setDisclaimerOpen] = useState(false)
  const disclaimerCloseTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  function openDisclaimer() {
    if (disclaimerCloseTimer.current) clearTimeout(disclaimerCloseTimer.current)
    setDisclaimerOpen(true)
  }
  function closeDisclaimer() {
    disclaimerCloseTimer.current = setTimeout(() => setDisclaimerOpen(false), 120)
  }

  function setField(key: keyof PolicyFields, val: string) {
    setFields(p => ({ ...p, [key]: val }))
  }

  function handleCopy() {
    navigator.clipboard?.writeText(generatedPolicy).catch(() => {})
    setCopied(true)
    setAwaitingConfirm(true)
    setTimeout(() => setCopied(false), 2200)
  }

  function handleManualConfirm() {
    setVerifying(true)
    showToast?.("Scanning your website for the privacy policy…")
    setTimeout(() => {
      setVerifying(false)
      onPrivacyPublish()
    }, 2200)
  }

  useEffect(() => {
    if (!privacyPublished) return
    const t = setTimeout(() => setPrivacyFaded(true), 1500)
    return () => clearTimeout(t)
  }, [privacyPublished])

  const generatedPolicy = POLICY_TEMPLATE({ ...fields, websiteUrl })
  const detectedUrl = privacyPublished ? `${websiteUrl}/privacy-policy` : ""

  const needsResolution = !privacyPublished

  return (
    <div className="space-y-2">
      {/* Privacy Policy URL — read-only scan result */}
      <div>
        <label className="block text-sm font-semibold text-foreground mb-1.5">
          <span className="text-red-500 mr-1">*</span>Privacy Policy URL
          <span className="ml-2 text-xs font-normal text-muted-foreground">— scanned from your website</span>
        </label>        <div className="relative">
          <input type="text" readOnly value={detectedUrl}
            placeholder="No privacy policy detected"
            className={cn(
              "w-full h-11 rounded-lg border px-3 pr-10 text-sm focus:outline-none transition-colors duration-700",
              simPrivacyRejected
                ? "border-red-400 bg-white text-foreground"
                : privacyPublished && !privacyFaded
                ? "border-emerald-300 bg-emerald-50 text-foreground"
                : privacyPublished && privacyFaded
                ? "border-border bg-white text-foreground"
                : showMissingError
                ? "border-red-300 bg-white placeholder:text-red-400"
                : "border-amber-300 bg-amber-50/40 placeholder:text-muted-foreground/60",
            )}
          />
          <span className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none">
            {privacyPublished
              ? <CheckCircle2 className={cn("h-4 w-4 transition-colors duration-700", privacyFaded ? "text-emerald-600/30" : "text-emerald-600")} />
              : simPrivacyRejected || showMissingError
              ? <XCircle className="h-4 w-4 text-red-500" />
              : <TriangleAlert className="h-4 w-4 text-amber-500" />}
          </span>
        </div>
        {privacyPublished && !privacyFaded && (
          <p className="mt-1.5 text-xs text-emerald-700 flex items-center gap-1.5">
            <CheckCircle2 className="h-3.5 w-3.5 shrink-0" />
            Privacy policy verified at {detectedUrl}
          </p>
        )}
        {showMissingError && !privacyPublished && (
          <InlineError message="A privacy policy is required to complete carrier registration." />
        )}
      </div>

      {/* Carrier rejection notice */}
      {simPrivacyRejected && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 space-y-3">
          <div className="flex items-start gap-2.5">
            <XCircle className="h-4 w-4 text-red-500 mt-0.5 shrink-0" />
            <div>
              <p className="text-sm font-medium text-red-900">Your privacy policy couldn't be verified by our carrier</p>
              <p className="text-xs text-red-700 mt-1 leading-relaxed">
                Our carrier checked your website but couldn't confirm a valid, publicly accessible privacy policy. This usually happens when the page is behind a login, set to draft, or the URL has changed. Use the form below to regenerate and republish it.
              </p>
            </div>
          </div>
          <div className="border-t border-red-200 pt-2.5 flex justify-end">
            <button type="button" onClick={onSimPrivacyDismiss}
              className="text-xs font-medium text-red-700 hover:text-red-900 transition-colors"
            >
              Got it — I'll fix this below →
            </button>
          </div>
        </div>
      )}

      {/* Resolution form — always shown when policy isn't published */}
      {needsResolution && (
        <div className="rounded-xl border border-amber-200 bg-amber-50/40 px-5 py-4 space-y-5">
          {/* Notice */}
          {!simPrivacyRejected && (
            <div className="flex items-start gap-2.5">
              <TriangleAlert className="h-4 w-4 text-amber-600 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-amber-900">No privacy policy found</p>
                <p className="text-xs text-amber-800 mt-0.5 leading-relaxed">
                  We scanned <span className="font-medium">{websiteUrl}</span> but didn't find a privacy policy page. Fill in your details below to generate one.
                </p>
              </div>
            </div>
          )}

          {/* Pre-filled callout — simple one-liner */}
          <div className="flex items-start gap-2.5 rounded-lg border border-amber-200 bg-white px-4 py-3">
            <CheckCircle2 className="h-4 w-4 text-emerald-600 shrink-0 mt-0.5" />
            <p className="text-xs text-zinc-700 leading-relaxed">
              We've pre-filled parts of this policy using the details you entered on this page. To update any of those details, edit the fields above and your policy will reflect the changes.
            </p>
          </div>

          {/* Required: message frequency — no default, must select */}
          <div>
            <label className="block text-[11px] font-semibold text-amber-900 mb-1.5">
              <span className="text-red-500 mr-1">*</span>How often will you send text messages?
            </label>
            <select
              value={fields.messageFrequency}
              onChange={(e) => setField("messageFrequency", e.target.value)}
              className={cn(
                "h-8 rounded-md border px-2.5 text-xs focus:outline-none focus:ring-2 focus:ring-amber-400/30 bg-white",
                fields.messageFrequency === ""
                  ? "border-amber-300 text-muted-foreground"
                  : "border-amber-200 text-foreground",
              )}
            >
              <option value="" disabled>Select frequency…</option>
              <option value="varies">Varies — frequency changes month to month</option>
              <option value="1">~1 message per month</option>
              <option value="2">~2 messages per month</option>
              <option value="4">~4 messages per month</option>
              <option value="8">~8 messages per month</option>
            </select>
            <p className="text-[11px] text-amber-700 mt-1">Required by carriers. You must select one — this appears in your policy's SMS section.</p>
          </div>

          {/* Required: retention periods — always shown, no pre-filled defaults */}
          <RetentionAccordion fields={fields} setField={setField} />

          {/* Live template preview — always visible */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold text-amber-900">Generated policy</p>
              {/* Disclaimer tooltip — far right */}
              <div className="relative flex items-center gap-1 cursor-default"
                onMouseEnter={openDisclaimer}
                onMouseLeave={closeDisclaimer}
              >
                <Info className="h-3.5 w-3.5 text-zinc-700" />
                <span className="text-[11px] font-medium text-zinc-700">Disclaimer</span>
                {disclaimerOpen && (
                  <div
                    onMouseEnter={openDisclaimer}
                    onMouseLeave={closeDisclaimer}
                    className="absolute bottom-full right-0 mb-2.5 w-96 rounded-xl border border-zinc-200 bg-white shadow-2xl z-50 overflow-hidden"
                  >
                    <div className="px-5 py-4 border-b border-zinc-100">
                      <p className="text-xs font-bold text-zinc-800 uppercase tracking-wide">Legal Disclaimer</p>
                    </div>
                    <div className="px-5 py-4 space-y-3 max-h-72 overflow-y-auto">
                      <p className="text-xs text-zinc-600 leading-relaxed">
                        This template was created by a general purpose large language model for informational purposes only and is <span className="font-semibold text-zinc-800">not legal advice</span>. It is intended as a starting point only and should not be relied upon as a substitute for consultation with qualified legal counsel. Use is at your own risk. Entrata shall not be liable for any damages, losses, or other consequences arising from its use or adaptation.
                      </p>
                      <p className="text-xs text-zinc-600 leading-relaxed">
                        Each organization's privacy practices, data processing activities, and regulatory obligations are unique. Applicable privacy laws and regulations vary by jurisdiction, industry, and the nature of personal data collected and processed. This template may not address all legal requirements applicable to your organization, including certain state or international privacy laws.
                      </p>
                      <p className="text-xs text-zinc-600 leading-relaxed">
                        Before using or adapting this template, you should conduct a thorough review of your organization's specific data collection and processing activities, assess all applicable legal and regulatory requirements, and consult with legal counsel to ensure compliance with all relevant laws.
                      </p>
                      <p className="text-xs text-zinc-600 leading-relaxed">
                        Privacy laws are subject to frequent amendment and evolving regulatory guidance; accordingly, you should periodically review and update any privacy notice derived from this template to ensure continued compliance.
                      </p>
                    </div>
                    {/* Arrow */}
                    <div className="absolute top-full right-4 w-0 h-0 border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-zinc-200" />
                  </div>
                )}
              </div>
            </div>
            <div className="rounded-lg border border-amber-200 bg-white p-3 max-h-52 overflow-y-auto">
              <pre className="text-[11px] text-foreground/75 leading-relaxed whitespace-pre-wrap font-sans">
                {generatedPolicy}
              </pre>
            </div>
          </div>

          {/* Action buttons */}
          <div className="border-t border-amber-200 pt-4 space-y-3">
            <div className="flex flex-wrap gap-2 items-center">
                {/* Publish button — disabled until policyReady */}
                <div className="relative group">
                  <button
                    type="button"
                    onClick={policyReady ? onPrivacyPublish : undefined}
                    disabled={!policyReady}
                    className={cn(
                      "h-9 px-4 rounded-lg text-xs font-medium flex items-center gap-1.5 transition-colors",
                      policyReady
                        ? "bg-zinc-900 text-white hover:bg-zinc-800 cursor-pointer"
                        : "bg-zinc-200 text-zinc-400 cursor-not-allowed",
                    )}
                  >
                    <Globe className="h-3.5 w-3.5" />
                    Publish to my website
                  </button>
                  {!policyReady && (
                    <div className="pointer-events-none absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 rounded-lg border border-zinc-200 bg-white shadow-xl px-3.5 py-3 opacity-0 group-hover:opacity-100 transition-opacity duration-150 z-50">
                      <p className="text-[11px] text-zinc-700 leading-relaxed">
                        Complete <span className="font-semibold">message frequency</span> and all <span className="font-semibold">data retention periods</span> above to unlock.
                      </p>
                      <div className="absolute top-full left-1/2 -translate-x-1/2 w-0 h-0 border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-zinc-200" />
                    </div>
                  )}
                </div>

                {/* Copy button — disabled until policyReady */}
                <div className="relative group">
                  <button
                    type="button"
                    onClick={policyReady ? handleCopy : undefined}
                    disabled={!policyReady}
                    className={cn(
                      "h-9 px-4 rounded-lg border text-xs font-medium flex items-center gap-1.5 transition-colors",
                      policyReady
                        ? "border-amber-300 bg-white text-amber-900 hover:border-amber-400 hover:bg-amber-50 cursor-pointer"
                        : "border-zinc-200 bg-zinc-50 text-zinc-400 cursor-not-allowed",
                    )}
                  >
                    {copied ? <><Check className="h-3.5 w-3.5 text-emerald-600" /> Copied!</> : <><Copy className="h-3.5 w-3.5" /> Copy policy text</>}
                  </button>
                  {!policyReady && (
                    <div className="pointer-events-none absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 rounded-lg border border-zinc-200 bg-white shadow-xl px-3.5 py-3 opacity-0 group-hover:opacity-100 transition-opacity duration-150 z-50">
                      <p className="text-[11px] text-zinc-700 leading-relaxed">
                        Complete <span className="font-semibold">message frequency</span> and all <span className="font-semibold">data retention periods</span> above to unlock.
                      </p>
                      <div className="absolute top-full left-1/2 -translate-x-1/2 w-0 h-0 border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-zinc-200" />
                    </div>
                  )}
                </div>
                {/* Always visible — disabled until policy is copied */}
                <div className="relative group">
                  <button
                    type="button"
                    onClick={awaitingConfirm && !verifying ? handleManualConfirm : undefined}
                    disabled={!awaitingConfirm || verifying}
                    className={cn(
                      "h-9 px-4 rounded-lg border text-xs font-medium flex items-center gap-1.5 transition-colors",
                      awaitingConfirm && !verifying
                        ? "border-zinc-300 bg-white text-foreground hover:border-zinc-400 cursor-pointer"
                        : "border-zinc-200 bg-zinc-50 text-zinc-400 cursor-not-allowed",
                    )}
                  >
                    {verifying
                      ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Verifying…</>
                      : <><RefreshCw className="h-3.5 w-3.5" /> I've added it — verify my site</>
                    }
                  </button>
                  {/* Tooltip shown when disabled */}
                  {!awaitingConfirm && (
                    <div className="pointer-events-none absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 rounded-lg border border-zinc-200 bg-white shadow-xl px-3.5 py-3 opacity-0 group-hover:opacity-100 transition-opacity duration-150 z-50">
                      <p className="text-[11px] text-zinc-700 leading-relaxed">
                        First, <span className="font-semibold">copy the policy text</span> using the button to the left, then paste it into your website. Once it's live, come back here and click this button to verify.
                      </p>
                      <div className="absolute top-full left-1/2 -translate-x-1/2 w-0 h-0 border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-zinc-200" />
                    </div>
                  )}
                </div>
              </div>
            <p className="text-[11px] text-amber-700 leading-relaxed">
              <span className="font-medium">Publish to my website</span> adds a <span className="font-mono bg-amber-100 px-1 rounded">/privacy-policy</span> page automatically.{" "}
              <span className="font-medium">Copy policy text</span> lets you paste it into your own CMS or third-party website.
            </p>
          </div>
        </div>
      )}
    </div>
  )
}

// ── Main page ────────────────────────────────────────────────────────────────

export function CompanyPage({ navigate, privacyPublished, onPrivacyPublish, brandStatus, showToast, simMode, onSimModeChange }: Props) {
  const [einRevealed, setEinRevealed] = useState(false)

  const [rejectedFields, setRejectedFields] = useState<Set<RejectedField>>(new Set())
  const [missingFields, setMissingFields] = useState<Set<RejectedField>>(new Set())
  const [privacyCarrierRejected, setPrivacyCarrierRejected] = useState(false)
  const [restarting, setRestarting] = useState(false)
  const [restartDone, setRestartDone] = useState(false)
  const [simFields, setSimFields] = useState<Record<string, string>>({})

  function triggerAutoSave(label: string) {
    showToast(`${label} saved`)
  }

  function activateMissingSim() {
    onSimModeChange("missing")
    setRejectedFields(new Set())
    setPrivacyCarrierRejected(false)
    setRestartDone(false)
    setRestarting(false)
    setMissingFields(new Set(Object.keys(CARRIER_REJECTION_MESSAGES) as RejectedField[]))
    setSimFields({
      "legal": "", "address-street": "", "address-city": "", "address-state": "", "address-zip": "",
      "phone": "", "website": "", "rep-name": "", "rep-email": "", "rep-phone": "",
    })
  }

  function activateRejectedSim() {
    onSimModeChange("rejected")
    setMissingFields(new Set())
    setRestartDone(false)
    setRestarting(false)
    setSimFields({})
    setRejectedFields(new Set(Object.keys(CARRIER_REJECTION_MESSAGES) as RejectedField[]))
    setPrivacyCarrierRejected(true)
  }

  function resetSim() {
    onSimModeChange("none")
    setRejectedFields(new Set())
    setMissingFields(new Set())
    setPrivacyCarrierRejected(false)
    setSimFields({})
    setRestarting(false)
    setRestartDone(false)
  }

  function dismissRejection(field: RejectedField) {
    setRejectedFields(prev => {
      const next = new Set(prev)
      next.delete(field)
      if (next.size === 0 && !privacyCarrierRejected) {
        setRestarting(true)
        setTimeout(() => { setRestarting(false); setRestartDone(true); onSimModeChange("none") }, 2500)
      }
      return next
    })
  }

  function dismissPrivacyRejection() {
    setPrivacyCarrierRejected(false)
    if (rejectedFields.size === 0) {
      setRestarting(true)
      setTimeout(() => { setRestarting(false); setRestartDone(true); onSimModeChange("none") }, 2500)
    }
  }

  useEffect(() => {
    if (brandStatus !== "approved") return
    showToast("Carrier registration approved — phone numbers are being set up")
  }, [brandStatus])

  function sv(key: string, fallback: string) {
    return simMode === "missing" && key in simFields ? simFields[key] : fallback
  }
  const isMissing = (f: RejectedField) => simMode === "missing" && missingFields.has(f)
  const isRejected = (f: RejectedField) => simMode === "rejected" && rejectedFields.has(f)
  const redBorder = (f: RejectedField) =>
    isMissing(f) || isRejected(f) ? "border-red-400 focus:ring-red-400/20" : undefined

  const websiteValue = sv("website", "https://www.sunsetproperties.com")

  return (
    <div className="p-6 md:p-8">
      {/* ── Sim buttons ───────────────────────────────────────────────────── */}
      <div className="fixed top-16 right-6 z-40 flex flex-col items-end gap-1.5">
        <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground/50 flex items-center gap-1">
          <FlaskConical className="h-3 w-3" /> Simulate
        </p>
        <div className="flex gap-2">
          <button type="button" onClick={activateMissingSim}
            className={cn(
              "inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium shadow-sm transition-colors",
              simMode === "missing" ? "border-amber-300 bg-amber-50 text-amber-800" : "border-border bg-white text-muted-foreground hover:text-foreground hover:border-zinc-400",
            )}
          >
            <TriangleAlert className="h-3.5 w-3.5" /> Missing fields
          </button>
          <button type="button" onClick={activateRejectedSim}
            className={cn(
              "inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium shadow-sm transition-colors",
              simMode === "rejected" ? "border-red-300 bg-red-50 text-red-800" : "border-border bg-white text-muted-foreground hover:text-foreground hover:border-zinc-400",
            )}
          >
            <XCircle className="h-3.5 w-3.5" /> Carrier rejection
          </button>
          {simMode !== "none" && (
            <button type="button" onClick={resetSim}
              className="inline-flex items-center gap-1 rounded-lg border border-border bg-white px-2.5 py-1.5 text-xs text-muted-foreground hover:text-foreground shadow-sm transition-colors"
            >
              <X className="h-3 w-3" /> Reset
            </button>
          )}
        </div>
        {simMode === "missing" && <p className="text-[11px] text-amber-700 bg-amber-50 border border-amber-200 rounded-md px-2.5 py-1">Showing: required fields not provided</p>}
        {simMode === "rejected" && !restarting && !restartDone && <p className="text-[11px] text-red-700 bg-red-50 border border-red-200 rounded-md px-2.5 py-1">Showing: all fields rejected by our carrier</p>}
      </div>

      <div className="mb-6">
        <button type="button" onClick={() => navigate("overview")}
          className={cn(buttonVariants({ variant: "ghost", size: "sm" }), "gap-1 -ml-2 text-muted-foreground")}
        >
          <ArrowLeft className="h-4 w-4" aria-hidden /> Overview
        </button>
      </div>

      <div className="flex-1 min-w-0 max-w-2xl space-y-8">

        <div>
          <h1 className="text-2xl font-bold tracking-tight">Carrier Compliance</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Confirm your business details so we can register your company with our carrier. This keeps your texts and calls compliant — without it, messages can be blocked or result in fines.
          </p>
        </div>

        {/* Restarting banner */}
        {restarting && (
          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 flex items-center gap-3">
            <Loader2 className="h-5 w-5 text-blue-600 animate-spin shrink-0" />
            <div>
              <p className="text-sm font-semibold text-blue-900">Restarting carrier registration…</p>
              <p className="text-xs text-blue-700 mt-0.5">We've received your updated information and are re-submitting. This usually takes around 15 minutes.</p>
            </div>
          </div>
        )}

        {/* Restart success */}
        {restartDone && (
          <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 flex items-center gap-3">
            <CheckCircle2 className="h-5 w-5 text-emerald-600 shrink-0" />
            <div>
              <p className="text-sm font-semibold text-emerald-900">Re-submitted successfully</p>
              <p className="text-xs text-emerald-700 mt-0.5">Your updated information has been sent to our carrier. We'll notify you once it's verified — typically within 15 minutes.</p>
            </div>
          </div>
        )}

        {/* ── Company Information ──────────────────────────────────────────── */}
        {!restarting && (
        <div className="space-y-5">
          <Field>
            <LabelWithInfo info={FIELD_INFO.legal}>Legal Business Name</LabelWithInfo>
            <input type="text"
              value={sv("legal", "Sunset Properties LLC")}
              placeholder="Enter your legal business name"
              onChange={(e) => setSimFields(p => ({ ...p, legal: e.target.value }))}
              onBlur={() => triggerAutoSave("Legal Business Name")}
              className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("legal"))}
            />
            {isMissing("legal") && <InlineError message={MISSING_MESSAGES["legal"]} />}
            {isRejected("legal") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["legal"]} onDismiss={() => dismissRejection("legal")} />}
          </Field>

          <Field>
            <LabelWithInfo info={FIELD_INFO.ein}>EIN (Federal Tax ID)</LabelWithInfo>
            <div className="relative">
              <input type="text" readOnly value={einRevealed ? PREFILLED_EIN : maskedEin}
                className={cn("w-full h-11 rounded-lg border bg-zinc-50 px-3 pr-10 text-sm text-muted-foreground cursor-default focus:outline-none", isRejected("ein") || isMissing("ein") ? "border-red-400" : "border-border")}
              />
              <button type="button" onClick={() => setEinRevealed(v => !v)} className="absolute right-3 top-1/2 -translate-y-1/2" aria-label={einRevealed ? "Hide EIN" : "Reveal EIN"}>
                <Lock className="h-3.5 w-3.5 text-muted-foreground hover:text-foreground transition-colors" />
              </button>
            </div>
            <p className="text-xs text-muted-foreground mt-1.5">Pulled from your Entrata account. Contact support to update.</p>
            {isMissing("ein") && <InlineError message={MISSING_MESSAGES["ein"]} />}
            {isRejected("ein") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["ein"]} onDismiss={() => dismissRejection("ein")} />}
          </Field>

          <Field>
            <LabelWithInfo info={FIELD_INFO.address}>Business Address</LabelWithInfo>
            <input type="text"
              value={sv("address-street", "123 Main Street, Suite 200")}
              placeholder="Street address"
              onChange={(e) => setSimFields(p => ({ ...p, "address-street": e.target.value }))}
              onBlur={() => triggerAutoSave("Business Address")}
              className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors mb-2", redBorder("address"))}
            />
            <div className="grid grid-cols-3 gap-2">
              {[
                { key: "address-city", fallback: "Austin", placeholder: "City" },
                { key: "address-state", fallback: "TX", placeholder: "State" },
                { key: "address-zip", fallback: "78701", placeholder: "ZIP" },
              ].map(({ key, fallback, placeholder }) => (
                <input key={key} type="text"
                  value={sv(key, fallback)} placeholder={placeholder}
                  onChange={(e) => setSimFields(p => ({ ...p, [key]: e.target.value }))}
                  className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("address"))}
                />
              ))}
            </div>
            {isMissing("address") && <InlineError message={MISSING_MESSAGES["address"]} />}
            {isRejected("address") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["address"]} onDismiss={() => dismissRejection("address")} />}
          </Field>

          <Field>
            <LabelWithInfo info={FIELD_INFO.phone}>Company Phone Number</LabelWithInfo>
            <input type="text"
              value={sv("phone", "(512) 555-0123")}
              placeholder="Enter your business phone number"
              onChange={(e) => setSimFields(p => ({ ...p, phone: e.target.value }))}
              onBlur={() => triggerAutoSave("Company Phone Number")}
              className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("phone"))}
            />
            {isMissing("phone") && <InlineError message={MISSING_MESSAGES["phone"]} />}
            {isRejected("phone") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["phone"]} onDismiss={() => dismissRejection("phone")} />}
          </Field>

          {/* Website URL + Privacy Policy URL — connected */}
          <div className="space-y-3 rounded-xl border border-border bg-zinc-50/50 p-4">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Website &amp; Privacy Policy</p>
            <p className="text-xs text-muted-foreground -mt-1">We scan your website to find your privacy policy — both are required for carrier registration.</p>

            <Field>
              <LabelWithInfo info={FIELD_INFO.website}>Website URL</LabelWithInfo>
              <input type="text"
                value={websiteValue}
                placeholder="https://yourbusiness.com"
                onChange={(e) => setSimFields(p => ({ ...p, website: e.target.value }))}
                onBlur={() => triggerAutoSave("Website URL")}
                className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("website"))}
              />
              {isMissing("website") && <InlineError message={MISSING_MESSAGES["website"]} />}
              {isRejected("website") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["website"]} onDismiss={() => dismissRejection("website")} />}
            </Field>

            <PrivacyPolicySection
              websiteUrl={websiteValue}
              privacyPublished={privacyPublished}
              onPrivacyPublish={onPrivacyPublish}
              simPrivacyRejected={privacyCarrierRejected}
              onSimPrivacyDismiss={dismissPrivacyRejection}
              showMissingError={isMissing("website")}
              showToast={showToast}
            />
          </div>
        </div>
        )}

        {/* ── Authorized Representative ────────────────────────────────────── */}
        {!restarting && (
        <div className="space-y-5">
          <div>
            <h2 className="text-lg font-bold tracking-tight">Authorized Representative</h2>
            <p className="text-sm text-muted-foreground mt-0.5">Contact person authorized to manage this account</p>
          </div>
          <Field>
            <LabelWithInfo info={FIELD_INFO.repName}>Full Name</LabelWithInfo>
            <input type="text"
              value={sv("rep-name", "Sarah Johnson")}
              placeholder="Full legal name"
              onChange={(e) => setSimFields(p => ({ ...p, "rep-name": e.target.value }))}
              onBlur={() => triggerAutoSave("Full Name")}
              className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("rep-name"))}
            />
            {isMissing("rep-name") && <InlineError message={MISSING_MESSAGES["rep-name"]} />}
            {isRejected("rep-name") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["rep-name"]} onDismiss={() => dismissRejection("rep-name")} />}
          </Field>
          <Field>
            <LabelWithInfo info={FIELD_INFO.repEmail}>Email Address</LabelWithInfo>
            <input type="text"
              value={sv("rep-email", "sarah.johnson@sunsetproperties.com")}
              placeholder="Email address"
              onChange={(e) => setSimFields(p => ({ ...p, "rep-email": e.target.value }))}
              onBlur={() => triggerAutoSave("Email Address")}
              className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("rep-email"))}
            />
            {isMissing("rep-email") && <InlineError message={MISSING_MESSAGES["rep-email"]} />}
            {isRejected("rep-email") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["rep-email"]} onDismiss={() => dismissRejection("rep-email")} />}
          </Field>
          <Field>
            <LabelWithInfo info={FIELD_INFO.repPhone}>Phone Number</LabelWithInfo>
            <input type="text"
              value={sv("rep-phone", "(512) 555-0124")}
              placeholder="Phone number"
              onChange={(e) => setSimFields(p => ({ ...p, "rep-phone": e.target.value }))}
              onBlur={() => triggerAutoSave("Phone Number")}
              className={cn("w-full h-11 rounded-lg border bg-white px-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-zinc-900/20 transition-colors", redBorder("rep-phone"))}
            />
            {isMissing("rep-phone") && <InlineError message={MISSING_MESSAGES["rep-phone"]} />}
            {isRejected("rep-phone") && <CarrierRejectionCard reason={CARRIER_REJECTION_MESSAGES["rep-phone"]} onDismiss={() => dismissRejection("rep-phone")} />}
          </Field>
        </div>
        )}

        {/* Brand submitting */}
        {brandStatus === "submitting" && !restarting && (
          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 flex items-center gap-3">
            <Loader2 className="h-5 w-5 text-blue-600 animate-spin shrink-0" />
            <div>
              <p className="text-sm font-semibold text-blue-900">Registering your business with our carrier…</p>
              <p className="text-xs text-blue-700 mt-0.5">This usually takes around 15 minutes. We'll notify you when it's approved.</p>
            </div>
          </div>
        )}

      </div>
    </div>
  )
}
