/* eslint-disable */
// @generated — do not edit manually.
//
// Canonical catalog of every Entrata API endpoint derived from the OpenAPI
// YAML specs checked into the monolith. This is the same data that powers
// https://docs.entrata.com/api/v1/documentation (for public RPCs) plus the
// per-domain internal Slim Swagger specs.
//
// Regenerate with:
//   npm run gen:api-catalog
//
// Source monolith: ~/Desktop/vhosts/docker-env/Entrata
// Generated at:    2026-04-23T23:05:21.057Z
// Total endpoints: 180
//   public-rpc:    122
//   internal-rest: 58

export type GeneratedApiSurface = "public-rpc" | "internal-rest";
export type GeneratedApiOperation = "read" | "action";

export interface GeneratedApiEntry {
  /** Stable id — matches what the PHP Action produces. */
  readonly id: string;
  readonly surface: GeneratedApiSurface;
  /** Tag / resource group (e.g. "applications", "Ar Codes"). */
  readonly resource: string;
  /** RPC method name or Slim operationId. */
  readonly method: string;
  /** HTTP verb — POST for public RPC, varies for internal REST. */
  readonly httpVerb: string;
  /** URL path template (may include {orgs} or {id}). */
  readonly path: string;
  /** Short human-readable label. */
  readonly summary: string;
  /** Longer description if available in the spec. */
  readonly description: string | null;
  /** UI bucket — "read" = Data Access, "action" = Skills. */
  readonly operation: GeneratedApiOperation;
  /** Repo-relative source YAML path. */
  readonly sourceFile: string;
}

export interface GeneratedApiSource {
  readonly kind: GeneratedApiSurface;
  readonly path: string;
  readonly endpointCount: number;
}

export const API_CATALOG_GENERATED_AT: string = "2026-04-23T23:05:21.057Z";

export const API_CATALOG_SOURCES: ReadonlyArray<GeneratedApiSource> = Object.freeze([
  { kind: "public-rpc", path: "www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml", endpointCount: 122 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/application/swagger20251202.yml", endpointCount: 10 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/assets-tracking/swagger20251202.yml", endpointCount: 1 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/consumergroup/swagger20251202.yml", endpointCount: 2 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/customerbilling/swagger20251202.yml", endpointCount: 3 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml", endpointCount: 27 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml", endpointCount: 6 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/onlineapplication/swagger20251202.yml", endpointCount: 4 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/oxp-financial/swagger20260106.yml", endpointCount: 2 },
  { kind: "internal-rest", path: "www/Entrata/rest/documentation/internal/oxp-revenue-protection/swagger20260129.yml", endpointCount: 3 },
]);
export const GENERATED_API_ENTRIES: ReadonlyArray<GeneratedApiEntry> = Object.freeze([
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-addons-customer-parking-assignments","surface":"internal-rest","resource":"AddOn Details","method":"POST /rest/internal/entratagpt/v1/addons/customer-parking-assignments","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/addons/customer-parking-assignments","summary":"Get customer parking assignments","description":"Returns parking assignments for customers including parking space numbers and group names. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-analytics-properties-evictions-count","surface":"internal-rest","resource":"Analytics","method":"POST /rest/internal/entratagpt/v1/analytics/properties-evictions-count","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/analytics/properties-evictions-count","summary":"Get properties evictions count","description":"Returns eviction counts by property including total evictions and monthly breakdown. Useful for portfolio analysis.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-analytics-property-lease-terms-move-ins-count","surface":"internal-rest","resource":"Analytics","method":"POST /rest/internal/entratagpt/v1/analytics/property-lease-terms-move-ins-count","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/analytics/property-lease-terms-move-ins-count","summary":"Get property lease terms move-ins count","description":"Returns lease terms move-in counts by property. Useful for analyzing lease term preferences and trends.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-analytics-resident-retention-rate","surface":"internal-rest","resource":"Analytics","method":"POST /rest/internal/entratagpt/v1/analytics/resident-retention-rate","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/analytics/resident-retention-rate","summary":"Get resident retention rate","description":"Returns resident retention rate across portfolio including retention ratios and lease counts by retention type.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.application.getAddOns","surface":"internal-rest","resource":"Application - Add-Ons","method":"getAddOns","httpVerb":"GET","path":"/v1/add-ons","summary":"Get application add-ons","description":"Retrieves add-ons for a specific application.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.addApplicationDocument","surface":"internal-rest","resource":"Application - Application Documents","method":"addApplicationDocument","httpVerb":"POST","path":"/v1/application_documents/add","summary":"Add application document","description":"Uploads a document to an application. Supports signature requirements and signed document uploads. Maximum file size is 50MB.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.updateApplicationDocument","surface":"internal-rest","resource":"Application - Application Documents","method":"updateApplicationDocument","httpVerb":"POST","path":"/v1/application_documents/update","summary":"Update application document","description":"Updates an existing application document. Can update file type, visibility settings, upload a new file to replace the existing one, or update verification status. Maximum file size is 50MB.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.getContactNeededLeads","surface":"internal-rest","resource":"Application - Contacts","method":"getContactNeededLeads","httpVerb":"POST","path":"/v1/contacts/contact-needed-leads","summary":"Get contact needed leads","description":"Returns list of leads that need to be contacted based on filter criteria. Supports filtering by property groups, priorities, agents, and properties with pagination.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.scheduleManualContact","surface":"internal-rest","resource":"Application - Contacts","method":"scheduleManualContact","httpVerb":"POST","path":"/v1/contacts/schedule","summary":"Schedule manual contact","description":"Schedules a manual contact (follow-up) for an application. The scheduled date must be in the future.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.getBalance","surface":"internal-rest","resource":"Application - Financial","method":"getBalance","httpVerb":"GET","path":"/v1/balance","summary":"Get application balance","description":"Retrieves the outstanding balance for an application.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.getDepositHeld","surface":"internal-rest","resource":"Application - Financial","method":"getDepositHeld","httpVerb":"GET","path":"/v1/deposit-held","summary":"Get deposit held","description":"Retrieves the deposit held amount for an application.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.getFinancialSummary","surface":"internal-rest","resource":"Application - Financial","method":"getFinancialSummary","httpVerb":"GET","path":"/v1/financial-summary","summary":"Get financial summary","description":"Retrieves comprehensive financial information for an application including balance, deposits, fees, recurring charges, and rent information. Response structure varies based on occupancy type (Student vs Conventional).","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.getTotalDeposit","surface":"internal-rest","resource":"Application - Financial","method":"getTotalDeposit","httpVerb":"GET","path":"/v1/total-deposit","summary":"Get total deposit","description":"Retrieves the total deposit amount for an application.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.application.addNote","surface":"internal-rest","resource":"Application - Notes","method":"addNote","httpVerb":"POST","path":"/v1/notes/add","summary":"Add note to application","description":"Adds a note to an application and publishes an event.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/application/swagger20251202.yml"},
  {"id":"rest.consumergroup.get-rest-internal-consumergroup-v1-arcodes","surface":"internal-rest","resource":"Ar Codes","method":"GET /rest/internal/consumergroup/v1/arcodes","httpVerb":"GET","path":"/rest/internal/consumergroup/v1/arcodes","summary":"Returns All ArCodes,","description":"This endpoint returns a Arcode with debitGlAccountId, creditGlAccountId","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/consumergroup/swagger20251202.yml"},
  {"id":"rest.consumergroup.get-rest-internal-consumergroup-v1-arcodes-id","surface":"internal-rest","resource":"Ar Codes","method":"GET /rest/internal/consumergroup/v1/arcodes/{id}","httpVerb":"GET","path":"/rest/internal/consumergroup/v1/arcodes/{id}","summary":"Returns ArCode for given Id","description":"This endpoint returns a Arcode with debitGlAccountId, creditGlAccountId","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/consumergroup/swagger20251202.yml"},
  {"id":"rest.assets-tracking.get-rest-internal-entrata-app-assets-tracking-v1-assets-fixed","surface":"internal-rest","resource":"Assets Tracking","method":"GET /rest/internal/entrata-app/assets-tracking/v1/assets/fixed","httpVerb":"GET","path":"/rest/internal/entrata-app/assets-tracking/v1/assets/fixed","summary":"Get Fixed Assets List for Bulk Disposition","description":"Retrieves a list of fixed assets available for bulk disposition for a specific property. Returns only assets that are not already retired and can be selected for disposition.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/assets-tracking/swagger20251202.yml"},
  {"id":"rest.customerbilling.get-rest-internal-entrata-app-customer-billing-v1-installment-plans-company-applications-companyapplicationid-properties-propertyid-lease-terms-leasetermid","surface":"internal-rest","resource":"Customer Billing","method":"GET /rest/internal/entrata-app/customer-billing/v1/installment-plans/company-applications/{companyApplicationId}/properties/{propertyId}/lease-terms/{leaseTermId}","httpVerb":"GET","path":"/rest/internal/entrata-app/customer-billing/v1/installment-plans/company-applications/{companyApplicationId}/properties/{propertyId}/lease-terms/{leaseTermId}","summary":"Get Installment Plans for a Company Application","description":"Retrieves installment plans for a specific company application. Returns detailed payment schedules and terms based on the provided parameters.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/customerbilling/swagger20251202.yml"},
  {"id":"rest.customerbilling.post-rest-internal-entrata-app-customer-billing-v1-apply-installment-plan","surface":"internal-rest","resource":"Customer Billing","method":"POST /rest/internal/entrata-app/customer-billing/v1/apply-installment-plan","httpVerb":"POST","path":"/rest/internal/entrata-app/customer-billing/v1/apply-installment-plan","summary":"Apply an Installment Plan Change to a Lease Interval","description":"Applies a new installment plan to a specified lease interval for a company within Entrata. This endpoint validates the user and request prior to performing the change and returns the resulting installment plan assignment and associated charges. The endpoint requires authentication and validates that the company user exists before processing the change.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/customerbilling/swagger20251202.yml"},
  {"id":"rest.customerbilling.post-rest-internal-entrata-app-customer-billing-v1-installment-plans","surface":"internal-rest","resource":"Customer Billing","method":"POST /rest/internal/entrata-app/customer-billing/v1/installment-plans","httpVerb":"POST","path":"/rest/internal/entrata-app/customer-billing/v1/installment-plans","summary":"Get Installment Plans","description":"Retrieves installment plans for a specific lease and lease interval. Returns detailed payment schedules and terms based on the provided parameters. The response structure varies based on the groupBy parameter: when groupBy is \"lease_term_id\", data is grouped by lease term with nested installment plans; when groupBy is null or \"id\", data is keyed by installment plan ID. When enableResidentFriendly is true, charge names are formatted for residents.\n**Authentication:** Basic Auth required (username: admin, password: admin)\n**Request Body:** JSON payload with required and optional parameters as specified in the request body schema below.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/customerbilling/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-birthdays","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/birthdays","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/birthdays","summary":"Get residents with birthdays this week","description":"Returns a list of residents with birthdays in the specified date range. Useful for identifying residents to send birthday greetings or special offers.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-communications","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/communications","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/communications","summary":"Get customer communications","description":"Returns communication history for a customer including communication type, notes, and scheduled dates. Supports pagination. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-contacts","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/contacts","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/contacts","summary":"Get customer contacts","description":"Returns emergency contact information for customers. Includes contact name, phone numbers, relationship, and address details.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-pets","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/pets","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/pets","summary":"Get customer pets","description":"Returns pet information for a customer. Can search by customer name or pet name. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-resident-profile","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/resident-profile","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/resident-profile","summary":"Get resident profile","description":"Returns comprehensive resident profile information including lease details, phone numbers, and pet information. Returns multiple customers if search criteria matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-vehicles","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/vehicles","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/vehicles","summary":"Get customer vehicles","description":"Returns vehicle information for customers at a property. Can filter by property ID, property name, or unit number.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-customers-without-photo-upload","surface":"internal-rest","resource":"Customer Details","method":"POST /rest/internal/entratagpt/v1/customers/without-photo-upload","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/customers/without-photo-upload","summary":"Get customers without photo upload","description":"Returns list of customers who have not uploaded photo IDs. Useful for compliance tracking and follow-up.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-delinquency-delinquency-details","surface":"internal-rest","resource":"Delinquency Details","method":"POST /rest/internal/entratagpt/v1/delinquency/delinquency-details","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/delinquency/delinquency-details","summary":"Get delinquency details","description":"Returns delinquency information for leases including notice details, amounts, and days late. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-documents-document-details","surface":"internal-rest","resource":"Document Details","method":"POST /rest/internal/entratagpt/v1/documents/document-details","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/documents/document-details","summary":"Get document details","description":"Returns document information for a unit/lease including file details, document types, and signature information. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.oxp-revenue-protection.get-rest-internal-revenue-protection-oxp-delinquency-v1-leases-leaseid-delinquency-status","surface":"internal-rest","resource":"Internal - Revenue Protection","method":"GET /rest/internal/revenue-protection/oxp/delinquency/v1/leases/{leaseId}/delinquency-status","httpVerb":"GET","path":"/rest/internal/revenue-protection/oxp/delinquency/v1/leases/{leaseId}/delinquency-status","summary":"Get Delinquency Status for Lease","description":"Returns the delinquency status for a specific lease, including whether it is delinquent and the associated delinquency policy document ID.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/oxp-revenue-protection/swagger20260129.yml"},
  {"id":"rest.oxp-revenue-protection.get-rest-internal-revenue-protection-oxp-delinquency-v1-properties-delinquency-data","surface":"internal-rest","resource":"Internal - Revenue Protection","method":"GET /rest/internal/revenue-protection/oxp/delinquency/v1/properties/delinquency-data","httpVerb":"GET","path":"/rest/internal/revenue-protection/oxp/delinquency/v1/properties/delinquency-data","summary":"Get Delinquency Data for Properties","description":"Returns paginated delinquency data for all delinquent leases in the specified properties, including resident information, notices sent, financial details, and next actions. Results are returned as a flat array.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/oxp-revenue-protection/swagger20260129.yml"},
  {"id":"rest.oxp-revenue-protection.post-rest-internal-revenue-protection-oxp-delinquency-v1-leases-leaseid-process-late-notice","surface":"internal-rest","resource":"Internal - Revenue Protection","method":"POST /rest/internal/revenue-protection/oxp/delinquency/v1/leases/{leaseId}/process-late-notice","httpVerb":"POST","path":"/rest/internal/revenue-protection/oxp/delinquency/v1/leases/{leaseId}/process-late-notice","summary":"Process Late Notice for Lease","description":"Processes and generates a late notice for a specific lease based on the provided delinquency policy and document.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/oxp-revenue-protection/swagger20260129.yml"},
  {"id":"rest.leadmanager.get-rest-internal-leadmanager-v1-application-statuses","surface":"internal-rest","resource":"LeadManager","method":"GET /rest/internal/leadmanager/v1/application-statuses","httpVerb":"GET","path":"/rest/internal/leadmanager/v1/application-statuses","summary":"Get Application Statuses","description":"Returns all available application statuses for the leads/applications filter, organized by stage (Guest Card, Pre-Qualification, Application, Lease). Includes only active statuses by default.","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml"},
  {"id":"rest.leadmanager.get-rest-internal-leadmanager-v1-archive-reasons","surface":"internal-rest","resource":"LeadManager","method":"GET /rest/internal/leadmanager/v1/archive-reasons","httpVerb":"GET","path":"/rest/internal/leadmanager/v1/archive-reasons","summary":"Get Archive Reasons","description":"Returns archive reasons list for lead archival with optional filtering by list type and property","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml"},
  {"id":"rest.leadmanager.post-rest-internal-leadmanager-v1-archive-guest-card","surface":"internal-rest","resource":"LeadManager","method":"POST /rest/internal/leadmanager/v1/archive-guest-card","httpVerb":"POST","path":"/rest/internal/leadmanager/v1/archive-guest-card","summary":"Archive Guest Card","description":"Archive a single guest card (application) with archive reason (list_item_id) and optional notes.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml"},
  {"id":"rest.leadmanager.post-rest-internal-leadmanager-v1-leads-contact-needed","surface":"internal-rest","resource":"LeadManager","method":"POST /rest/internal/leadmanager/v1/leads-contact-needed","httpVerb":"POST","path":"/rest/internal/leadmanager/v1/leads-contact-needed","summary":"Get Leads Contact Needed","description":"Returns a list of leads/applications that need contact, matching the dashboard contact needed view.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml"},
  {"id":"rest.leadmanager.post-rest-internal-leadmanager-v1-schedule-manual-contact","surface":"internal-rest","resource":"LeadManager","method":"POST /rest/internal/leadmanager/v1/schedule-manual-contact","httpVerb":"POST","path":"/rest/internal/leadmanager/v1/schedule-manual-contact","summary":"Schedule Manual Contact","description":"Schedule a manual contact (follow-up) for a guest card (application) with assigned company employee and scheduled date. The scheduled date must be in the future.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml"},
  {"id":"rest.leadmanager.post-rest-internal-leadmanager-v1-leads","surface":"internal-rest","resource":"Leads","method":"POST /rest/internal/leadmanager/v1/leads","httpVerb":"POST","path":"/rest/internal/leadmanager/v1/leads","summary":"Get Leads","description":"Returns a list of Applicants based on filter criteria provided in the request body. Supports filtering by property IDs, applicant ID, name, telephone, email, status IDs, and product IDs. Supports date range filtering and pagination. Sorting is supported by the sortBy and sortOrder parameters.\n *     Allowed values for sortBy: dateCreated, status, sources, name, property, lastContactDate, lastContact, lastName\n *     Allowed values for sortOrder: ASC, DESC\n *     Default sort order: DESC\n *     Default page: 1\n *     Default page size: 100\n *     Maximum page size: 100\n *     Important: StatusIds filter required application_stage_status_ids to filter by status.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/leadmanager/swagger20260113.yml"},
  {"id":"rest.oxp-financial.get-rest-internal-oxp-financial-v1-leases-leaseid-ledger-balance","surface":"internal-rest","resource":"Lease Balance","method":"GET /rest/internal/oxp-financial/v1/leases/{leaseId}/ledger-balance","httpVerb":"GET","path":"/rest/internal/oxp-financial/v1/leases/{leaseId}/ledger-balance","summary":"Returns lease balance for given lease ID","description":"This endpoint returns lease balance of given lease","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/oxp-financial/swagger20260106.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-expiring-leases","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/expiring-leases","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/expiring-leases","summary":"Get expiring leases","description":"Returns list of leases that are expiring within a specified date range. Includes lease dates, status, and interval type.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-interval-details","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/interval-details","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/interval-details","summary":"Get lease interval details","description":"Returns lease interval details for renewals and month-to-month leases. Includes active lease information and future interval details if available.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-leases-by-term-month","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/leases-by-term-month","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/leases-by-term-month","summary":"Get leases by term month","description":"Returns leases filtered by lease term month. Useful for analyzing lease term distribution.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-pending-evictions","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/pending-evictions","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/pending-evictions","summary":"Get pending evictions","description":"Returns list of leases with pending eviction proceedings. Includes lease ID, unit number, resident name, and termination start date.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-placed-on-notice","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/placed-on-notice","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/placed-on-notice","summary":"Get leases placed on notice","description":"Returns list of leases that have been placed on notice. Includes notice date and move-out date.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-scheduled-move-ins","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/scheduled-move-ins","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/scheduled-move-ins","summary":"Get scheduled move-ins","description":"Returns list of scheduled move-ins within a specified date range. Useful for move-in preparation and scheduling.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-unsigned-renewals","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/unsigned-renewals","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/unsigned-renewals","summary":"Get unsigned renewals","description":"Returns list of lease renewals that have not been signed. Includes renewal date and lease term information.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-leases-violations","surface":"internal-rest","resource":"Lease Details","method":"POST /rest/internal/entratagpt/v1/leases/violations","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/leases/violations","summary":"Get lease violations","description":"Returns list of lease violations including violation type, name, datetime, and resolution status.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-maintenance-maintenance-details","surface":"internal-rest","resource":"Maintenance Details","method":"POST /rest/internal/entratagpt/v1/maintenance/maintenance-details","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/maintenance/maintenance-details","summary":"Get maintenance request details","description":"Returns maintenance request details including status, problem type, location, and resolution information. Supports filtering by property, customer, unit, and date range. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.onlineapplication.getApplicationDetails","surface":"internal-rest","resource":"Online Applications","method":"getApplicationDetails","httpVerb":"GET","path":"/rest/internal/online-application/v1/applications/{id}","summary":"Retrieve application details by application ID","description":"Returns detailed application information including all applicants with their progress, steps, pets, and vehicles","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/onlineapplication/swagger20251202.yml"},
  {"id":"rest.onlineapplication.getApplicationsList","surface":"internal-rest","resource":"Online Applications","method":"getApplicationsList","httpVerb":"GET","path":"/rest/internal/online-application/v1/applications","summary":"Retrieve applications by applicant ID","description":"Returns a paginated list of applications for a specific applicant with nested applicant details","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/onlineapplication/swagger20251202.yml"},
  {"id":"rest.onlineapplication.getAffordableSubsidyTypes","surface":"internal-rest","resource":"Online Applications - Affordable","method":"getAffordableSubsidyTypes","httpVerb":"GET","path":"/rest/internal/online-application/v1/subsidy-types","summary":"Retrieve affordable subsidy types","description":"Returns a list of all active affordable subsidy types","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/onlineapplication/swagger20251202.yml"},
  {"id":"rest.onlineapplication.getApplicationPets","surface":"internal-rest","resource":"Online Applications - Customers","method":"getApplicationPets","httpVerb":"GET","path":"/rest/internal/online-application/v1/pets","summary":"Retrieve application pets","description":"Returns a list of pets for a specific application","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/onlineapplication/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-payments-lease-payment-details","surface":"internal-rest","resource":"Payment Details","method":"POST /rest/internal/entratagpt/v1/payments/lease-payment-details","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/payments/lease-payment-details","summary":"Get lease payment details","description":"Returns comprehensive payment history for a lease including total payments, last payment information, and payment status. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.oxp-financial.get-rest-internal-oxp-financial-v1-leases-leaseid-security-deposit","surface":"internal-rest","resource":"Security Deposit","method":"GET /rest/internal/oxp-financial/v1/leases/{leaseId}/security-deposit","httpVerb":"GET","path":"/rest/internal/oxp-financial/v1/leases/{leaseId}/security-deposit","summary":"Returns security deposit details for given Lease ID","description":"This endpoint returns security deposit details of given lease","operation":"read","sourceFile":"www/Entrata/rest/documentation/internal/oxp-financial/swagger20260106.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-transactions-leases-with-pending-payments","surface":"internal-rest","resource":"Transaction Details","method":"POST /rest/internal/entratagpt/v1/transactions/leases-with-pending-payments","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/transactions/leases-with-pending-payments","summary":"Get leases with pending payments","description":"Returns leases with pending payment transactions including charge codes, amounts, and post dates.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-transactions-residents-with-balance-due","surface":"internal-rest","resource":"Transaction Details","method":"POST /rest/internal/entratagpt/v1/transactions/residents-with-balance-due","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/transactions/residents-with-balance-due","summary":"Get residents with balance due","description":"Returns list of residents with outstanding balances. Supports filtering by date ranges, amounts, and property. Returns multiple customers if search matches multiple records.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-unit-spaces-unit-lease-details","surface":"internal-rest","resource":"Unit Space Details","method":"POST /rest/internal/entratagpt/v1/unit-spaces/unit-lease-details","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/unit-spaces/unit-lease-details","summary":"Get unit lease details","description":"Returns lease details for a specific unit including resident information, lease dates, status, and customer relationship details.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rest.entratagpt.post-rest-internal-entratagpt-v1-unit-spaces-vacant-units","surface":"internal-rest","resource":"Unit Space Details","method":"POST /rest/internal/entratagpt/v1/unit-spaces/vacant-units","httpVerb":"POST","path":"/rest/internal/entratagpt/v1/unit-spaces/vacant-units","summary":"Get vacant units","description":"Returns list of vacant units with availability dates and monthly rent information.","operation":"action","sourceFile":"www/Entrata/rest/documentation/internal/entratagpt/swagger20251202.yml"},
  {"id":"rpc.applications.getCompanyApplications","surface":"public-rpc","resource":"applications","method":"getCompanyApplications","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Get company applications","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.sendApplicantGeneralDetails","surface":"public-rpc","resource":"applications","method":"sendApplicantGeneralDetails","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Send applicant general details","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.sendApplication","surface":"public-rpc","resource":"applications","method":"sendApplication","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Send application","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.sendApplicationAddOns","surface":"public-rpc","resource":"applications","method":"sendApplicationAddOns","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Send application add ons","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.sendApplicationEmployers","surface":"public-rpc","resource":"applications","method":"sendApplicationEmployers","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Send application employers","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.sendApplicationPets","surface":"public-rpc","resource":"applications","method":"sendApplicationPets","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Send application pets","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.sendApplicationVehicles","surface":"public-rpc","resource":"applications","method":"sendApplicationVehicles","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Send application vehicles","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.applications.updateApplication","surface":"public-rpc","resource":"applications","method":"updateApplication","httpVerb":"POST","path":"/{orgs}/v1/applications","summary":"Update application","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.arcodes.getArCodes","surface":"public-rpc","resource":"arcodes","method":"getArCodes","httpVerb":"POST","path":"/{orgs}/v1/arcodes","summary":"Get ar codes","description":"Returns all AR codes for a specified management company.","operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.arpayments.getArPayments","surface":"public-rpc","resource":"arpayments","method":"getArPayments","httpVerb":"POST","path":"/{orgs}/v1/arpayments","summary":"Get ar payments","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.artransactions.getArInvoices","surface":"public-rpc","resource":"artransactions","method":"getArInvoices","httpVerb":"POST","path":"/{orgs}/v1/artransactions","summary":"Get ar invoices","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.artransactions.getLeaseArTransactions","surface":"public-rpc","resource":"artransactions","method":"getLeaseArTransactions","httpVerb":"POST","path":"/{orgs}/v1/artransactions","summary":"Get lease ar transactions","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.artransactions.getMitsLeaseArTransactions","surface":"public-rpc","resource":"artransactions","method":"getMitsLeaseArTransactions","httpVerb":"POST","path":"/{orgs}/v1/artransactions","summary":"Get mits lease ar transactions","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.artransactions.sendLeaseArTransactionReversals","surface":"public-rpc","resource":"artransactions","method":"sendLeaseArTransactionReversals","httpVerb":"POST","path":"/{orgs}/v1/artransactions","summary":"Send lease ar transaction reversals","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.artransactions.sendLeaseArTransactions","surface":"public-rpc","resource":"artransactions","method":"sendLeaseArTransactions","httpVerb":"POST","path":"/{orgs}/v1/artransactions","summary":"Send lease ar transactions","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.communications.getMarketingPreferencePickList","surface":"public-rpc","resource":"communications","method":"getMarketingPreferencePickList","httpVerb":"POST","path":"/{orgs}/v1/communications","summary":"Get marketing preference pick list","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.communications.getMarketingPreferences","surface":"public-rpc","resource":"communications","method":"getMarketingPreferences","httpVerb":"POST","path":"/{orgs}/v1/communications","summary":"Get marketing preferences","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.communications.sendMarketingPreferences","surface":"public-rpc","resource":"communications","method":"sendMarketingPreferences","httpVerb":"POST","path":"/{orgs}/v1/communications","summary":"Send marketing preferences","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.getCustomers","surface":"public-rpc","resource":"customers","method":"getCustomers","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Get customers","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.getCustomerTestimonials","surface":"public-rpc","resource":"customers","method":"getCustomerTestimonials","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Get customer testimonials","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.getTestimonialPickLists","surface":"public-rpc","resource":"customers","method":"getTestimonialPickLists","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Get testimonial pick lists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.searchCustomers","surface":"public-rpc","resource":"customers","method":"searchCustomers","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Search customers","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.sendCustomerTestimonials","surface":"public-rpc","resource":"customers","method":"sendCustomerTestimonials","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Send customer testimonials","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.updateCustomers","surface":"public-rpc","resource":"customers","method":"updateCustomers","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Update customers","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.updateCustomerTestimonials","surface":"public-rpc","resource":"customers","method":"updateCustomerTestimonials","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Update customer testimonials","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.customers.updatePropertyResponse","surface":"public-rpc","resource":"customers","method":"updatePropertyResponse","httpVerb":"POST","path":"/{orgs}/v1/customers","summary":"Update property response","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getApCodes","surface":"public-rpc","resource":"financial","method":"getApCodes","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get ap codes","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getBankAccounts","surface":"public-rpc","resource":"financial","method":"getBankAccounts","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get bank accounts","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getBudgetActuals","surface":"public-rpc","resource":"financial","method":"getBudgetActuals","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get budget actuals","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getBudgets","surface":"public-rpc","resource":"financial","method":"getBudgets","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get budgets","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getFinancialPickListRequest","surface":"public-rpc","resource":"financial","method":"getFinancialPickListRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get financial pick list request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getGlTransactionsRequest","surface":"public-rpc","resource":"financial","method":"getGlTransactionsRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get gl transactions request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getGlTreesRequest","surface":"public-rpc","resource":"financial","method":"getGlTreesRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get gl trees request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getJobCategoriesRequest","surface":"public-rpc","resource":"financial","method":"getJobCategoriesRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get job categories request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getJobCostBudgetsRequest","surface":"public-rpc","resource":"financial","method":"getJobCostBudgetsRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get job cost budgets request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getJobsRequest","surface":"public-rpc","resource":"financial","method":"getJobsRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get jobs request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.getTransactionTagListsRequest","surface":"public-rpc","resource":"financial","method":"getTransactionTagListsRequest","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Get transaction tag lists request","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.markGlTransactionsExported","surface":"public-rpc","resource":"financial","method":"markGlTransactionsExported","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Mark gl transactions exported","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.sendBudgets","surface":"public-rpc","resource":"financial","method":"sendBudgets","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Send budgets","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.sendJournalEntries","surface":"public-rpc","resource":"financial","method":"sendJournalEntries","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Send journal entries","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.financial.updateBudgets","surface":"public-rpc","resource":"financial","method":"updateBudgets","httpVerb":"POST","path":"/{orgs}/v1/financial","summary":"Update budgets","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.applyQuote","surface":"public-rpc","resource":"leads","method":"applyQuote","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Apply quote","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.generateQuotes","surface":"public-rpc","resource":"leads","method":"generateQuotes","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Generate quotes","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.getLeadEvents","surface":"public-rpc","resource":"leads","method":"getLeadEvents","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Get lead events","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.getLeadPickLists","surface":"public-rpc","resource":"leads","method":"getLeadPickLists","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Get lead pick lists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.getLeads","surface":"public-rpc","resource":"leads","method":"getLeads","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Get leads","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.getMitsLeads","surface":"public-rpc","resource":"leads","method":"getMitsLeads","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Get mits leads","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.getQuotes","surface":"public-rpc","resource":"leads","method":"getQuotes","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Get quotes","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.sendLeads","surface":"public-rpc","resource":"leads","method":"sendLeads","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Send leads","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.sendMitsLeads","surface":"public-rpc","resource":"leads","method":"sendMitsLeads","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Send mits leads","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leads.updateLeads","surface":"public-rpc","resource":"leads","method":"updateLeads","httpVerb":"POST","path":"/{orgs}/v1/leads","summary":"Update leads","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.cancelLease","surface":"public-rpc","resource":"leases","method":"cancelLease","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Cancel lease","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getEvictedLeases","surface":"public-rpc","resource":"leases","method":"getEvictedLeases","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get evicted leases","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getExpiringLeases","surface":"public-rpc","resource":"leases","method":"getExpiringLeases","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get expiring leases","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getLeaseDetails","surface":"public-rpc","resource":"leases","method":"getLeaseDetails","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get lease details","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getLeaseDocuments","surface":"public-rpc","resource":"leases","method":"getLeaseDocuments","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get lease documents","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getLeaseDocumentsList","surface":"public-rpc","resource":"leases","method":"getLeaseDocumentsList","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get lease documents list","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getLeasePickList","surface":"public-rpc","resource":"leases","method":"getLeasePickList","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get lease pick list","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getLeases","surface":"public-rpc","resource":"leases","method":"getLeases","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get leases","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getMitsCollections","surface":"public-rpc","resource":"leases","method":"getMitsCollections","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get mits collections","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getMitsLeases","surface":"public-rpc","resource":"leases","method":"getMitsLeases","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get mits leases","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getParcelAlerts","surface":"public-rpc","resource":"leases","method":"getParcelAlerts","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get parcel alerts","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.getRentersInsurancePolicies","surface":"public-rpc","resource":"leases","method":"getRentersInsurancePolicies","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Get renters insurance policies","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.moveInLease","surface":"public-rpc","resource":"leases","method":"moveInLease","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Move in lease","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.moveOutLease","surface":"public-rpc","resource":"leases","method":"moveOutLease","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Move out lease","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.onNoticeLease","surface":"public-rpc","resource":"leases","method":"onNoticeLease","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"On notice lease","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.sendLeaseActivities","surface":"public-rpc","resource":"leases","method":"sendLeaseActivities","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Send lease activities","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.sendLeaseDocuments","surface":"public-rpc","resource":"leases","method":"sendLeaseDocuments","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Send lease documents","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.sendLeases","surface":"public-rpc","resource":"leases","method":"sendLeases","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Send leases","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.sendRentersInsurancePolicies","surface":"public-rpc","resource":"leases","method":"sendRentersInsurancePolicies","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Send renters insurance policies","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.sendRoommateGroups","surface":"public-rpc","resource":"leases","method":"sendRoommateGroups","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Send roommate groups","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.sendScheduledCharges","surface":"public-rpc","resource":"leases","method":"sendScheduledCharges","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Send scheduled charges","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.updateLease","surface":"public-rpc","resource":"leases","method":"updateLease","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Update lease","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leases.updateScheduledCharges","surface":"public-rpc","resource":"leases","method":"updateScheduledCharges","httpVerb":"POST","path":"/{orgs}/v1/leases","summary":"Update scheduled charges","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leasingcenter.getCallLogs","surface":"public-rpc","resource":"leasingcenter","method":"getCallLogs","httpVerb":"POST","path":"/{orgs}/v1/leasingcenter","summary":"Get call logs","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.leasingcenter.getLeasingCenterPickLists","surface":"public-rpc","resource":"leasingcenter","method":"getLeasingCenterPickLists","httpVerb":"POST","path":"/{orgs}/v1/leasingcenter","summary":"Get leasing center pick lists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.maintenance.getInspections","surface":"public-rpc","resource":"maintenance","method":"getInspections","httpVerb":"POST","path":"/{orgs}/v1/maintenance","summary":"Get inspections","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.maintenance.getInspectionTemplates","surface":"public-rpc","resource":"maintenance","method":"getInspectionTemplates","httpVerb":"POST","path":"/{orgs}/v1/maintenance","summary":"Get inspection templates","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.maintenance.getWorkOrderPickLists","surface":"public-rpc","resource":"maintenance","method":"getWorkOrderPickLists","httpVerb":"POST","path":"/{orgs}/v1/maintenance","summary":"Get work order pick lists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.maintenance.getWorkOrders","surface":"public-rpc","resource":"maintenance","method":"getWorkOrders","httpVerb":"POST","path":"/{orgs}/v1/maintenance","summary":"Get work orders","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.maintenance.sendWorkOrders","surface":"public-rpc","resource":"maintenance","method":"sendWorkOrders","httpVerb":"POST","path":"/{orgs}/v1/maintenance","summary":"Send work orders","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.maintenance.updateWorkOrders","surface":"public-rpc","resource":"maintenance","method":"updateWorkOrders","httpVerb":"POST","path":"/{orgs}/v1/maintenance","summary":"Update work orders","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.pricing.getPricingPicklists","surface":"public-rpc","resource":"pricing","method":"getPricingPicklists","httpVerb":"POST","path":"/{orgs}/v1/pricing","summary":"Get pricing picklists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.pricing.insertPricing","surface":"public-rpc","resource":"pricing","method":"insertPricing","httpVerb":"POST","path":"/{orgs}/v1/pricing","summary":"Insert pricing","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.pricing.sendBudgetedRent","surface":"public-rpc","resource":"pricing","method":"sendBudgetedRent","httpVerb":"POST","path":"/{orgs}/v1/pricing","summary":"Send budgeted rent","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getAmenityReservations","surface":"public-rpc","resource":"properties","method":"getAmenityReservations","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get amenity reservations","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getCalendarAvailability","surface":"public-rpc","resource":"properties","method":"getCalendarAvailability","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get calendar availability","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getFloorPlans","surface":"public-rpc","resource":"properties","method":"getFloorPlans","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get floor plans","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getPetTypes","surface":"public-rpc","resource":"properties","method":"getPetTypes","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get pet types","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getProperties","surface":"public-rpc","resource":"properties","method":"getProperties","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get properties","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getPropertyAddOns","surface":"public-rpc","resource":"properties","method":"getPropertyAddOns","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get property add ons","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getPropertyAnnouncements","surface":"public-rpc","resource":"properties","method":"getPropertyAnnouncements","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get property announcements","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getPropertyPickLists","surface":"public-rpc","resource":"properties","method":"getPropertyPickLists","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get property pick lists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getRentableItems","surface":"public-rpc","resource":"properties","method":"getRentableItems","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get rentable items","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getReservableAmenities","surface":"public-rpc","resource":"properties","method":"getReservableAmenities","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get reservable amenities","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.getWebsites","surface":"public-rpc","resource":"properties","method":"getWebsites","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Get websites","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.sendFloorplans","surface":"public-rpc","resource":"properties","method":"sendFloorplans","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Send floorplans","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.properties.sendRentableItems","surface":"public-rpc","resource":"properties","method":"sendRentableItems","httpVerb":"POST","path":"/{orgs}/v1/properties","summary":"Send rentable items","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.getAmenities","surface":"public-rpc","resource":"propertyunits","method":"getAmenities","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Get amenities","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.getMitsPropertyUnits","surface":"public-rpc","resource":"propertyunits","method":"getMitsPropertyUnits","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Get mits property units","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.getPropertyUnits","surface":"public-rpc","resource":"propertyunits","method":"getPropertyUnits","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Get property units","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.getSpecials","surface":"public-rpc","resource":"propertyunits","method":"getSpecials","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Get specials","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.getUnitsAvailabilityAndPricing","surface":"public-rpc","resource":"propertyunits","method":"getUnitsAvailabilityAndPricing","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Get units availability and pricing","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.getUnitTypes","surface":"public-rpc","resource":"propertyunits","method":"getUnitTypes","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Get unit types","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.sendAmenities","surface":"public-rpc","resource":"propertyunits","method":"sendAmenities","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Send amenities","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.sendPropertyUnits","surface":"public-rpc","resource":"propertyunits","method":"sendPropertyUnits","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Send property units","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.propertyunits.updateAmenities","surface":"public-rpc","resource":"propertyunits","method":"updateAmenities","httpVerb":"POST","path":"/{orgs}/v1/propertyunits","summary":"Update amenities","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.status.getStatus","surface":"public-rpc","resource":"status","method":"getStatus","httpVerb":"POST","path":"/{orgs}/v1/status","summary":"Get status","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getInvoices","surface":"public-rpc","resource":"vendors","method":"getInvoices","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get invoices","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getPoReceivingRecords","surface":"public-rpc","resource":"vendors","method":"getPoReceivingRecords","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get po receiving records","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getPurchaseOrders","surface":"public-rpc","resource":"vendors","method":"getPurchaseOrders","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get purchase orders","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getTaxFormData","surface":"public-rpc","resource":"vendors","method":"getTaxFormData","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get tax form data","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getVendorLocations","surface":"public-rpc","resource":"vendors","method":"getVendorLocations","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get vendor locations","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getVendorPickLists","surface":"public-rpc","resource":"vendors","method":"getVendorPickLists","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get vendor pick lists","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.getVendors","surface":"public-rpc","resource":"vendors","method":"getVendors","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Get vendors","description":null,"operation":"read","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.markInvoicesExported","surface":"public-rpc","resource":"vendors","method":"markInvoicesExported","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Mark invoices exported","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.sendInvoices","surface":"public-rpc","resource":"vendors","method":"sendInvoices","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Send invoices","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.sendPurchaseOrders","surface":"public-rpc","resource":"vendors","method":"sendPurchaseOrders","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Send purchase orders","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.sendVendors","surface":"public-rpc","resource":"vendors","method":"sendVendors","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Send vendors","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.updateInvoices","surface":"public-rpc","resource":"vendors","method":"updateInvoices","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Update invoices","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.updateVendors","surface":"public-rpc","resource":"vendors","method":"updateVendors","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Update vendors","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
  {"id":"rpc.vendors.voidApPayments","surface":"public-rpc","resource":"vendors","method":"voidApPayments","httpVerb":"POST","path":"/{orgs}/v1/vendors","summary":"Void ap payments","description":null,"operation":"action","sourceFile":"www/Entrata/api_documentation/specs/entrata_rpc_openapi_specs.yaml"},
]);
