import type { LiveConversation } from "@/components/conversation-detail-sheet";

export const LIVE_CONVERSATIONS: LiveConversation[] = [
  {
    id: "lc-1",
    resident: "Maria Santos",
    unit: null,
    type: "lead",
    agent: "Leasing",
    assignee: "ELI+ Leasing AI",
    property: "Property A",
    channel: "Web Chat",
    time: "just now",
    messages: [
      { id: "m1", role: "agent", text: "Hi Maria! Thanks for reaching out. I'd love to help you find the perfect apartment. What are you looking for?" },
      { id: "m2", role: "resident", text: "Hi! I'm looking for a 1-bedroom, ideally with in-unit laundry. My budget is around $1,800/mo." },
      { id: "m3", role: "agent", text: "Great news — we have three 1-bedroom units available that fit your criteria. Unit 205 and Unit 310 both have in-unit washer/dryer and are listed at $1,750/mo. Would you like to schedule a tour?" },
      { id: "m4", role: "resident", text: "That sounds great — can I schedule a tour for Saturday morning?" },
    ],
  },
  {
    id: "lc-2",
    resident: "Robert Hernandez",
    unit: "Unit 318",
    type: "resident",
    agent: "Payments",
    assignee: "Sarah Chen",
    property: "Property B",
    channel: "Resident Portal",
    time: "2m ago",
    messages: [
      { id: "m1", role: "agent", text: "Hi Robert, this is a friendly reminder that your rent of $1,650 is due on March 1st. Would you like to make a payment now?" },
      { id: "m2", role: "resident", text: "Hey, I'm a little tight this month. Can I split this into two payments this month?" },
      { id: "m3", role: "agent", text: "I understand. Let me check what options are available for your account. One moment please." },
    ],
  },
  {
    id: "lc-3",
    resident: "Tina Washington",
    unit: "Unit 517",
    type: "resident",
    agent: "Maintenance",
    assignee: "ELI+ Maintenance AI",
    property: "Property A",
    channel: "SMS",
    time: "8m ago",
    messages: [
      { id: "m1", role: "resident", text: "The kitchen faucet started leaking again this morning. This is the second time in two months." },
      { id: "m2", role: "agent", text: "I'm sorry to hear that, Tina. I'll create a work order right away. Is there a preferred time for maintenance to come by?" },
      { id: "m3", role: "resident", text: "Anytime after 2pm works for me." },
    ],
  },
  {
    id: "lc-4",
    resident: "James Park",
    unit: "Unit 204",
    type: "resident",
    agent: "Renewal",
    assignee: "ELI+ Renewals AI",
    property: "Property C",
    channel: "Email",
    time: "12m ago",
    messages: [
      { id: "m1", role: "agent", text: "Hi James, your lease is coming up for renewal on April 30th. We'd love to keep you! We have a renewal offer ready for you." },
      { id: "m2", role: "resident", text: "I'd like to know more about the renewal offer you sent. What's the new rate?" },
      { id: "m3", role: "agent", text: "Your current rate is $1,900/mo. We're offering a 12-month renewal at $1,950/mo — just a 2.6% increase, which is below market average for the area." },
    ],
  },
  {
    id: "lc-5",
    resident: "Angela Foster",
    unit: "Unit 102",
    type: "resident",
    agent: "Payments",
    assignee: "ELI+ Payments AI",
    property: "Property A",
    channel: "Resident Portal",
    time: "15m ago",
    messages: [
      { id: "m1", role: "resident", text: "Is there a way to set up autopay for my rent?" },
      { id: "m2", role: "agent", text: "Absolutely, Angela! You can set up autopay through the resident portal. Would you like me to send you the direct link?" },
    ],
  },
  {
    id: "lc-6",
    resident: "David Kim",
    unit: null,
    type: "lead",
    agent: "Leasing",
    assignee: "ELI+ Leasing AI",
    property: "Property B",
    channel: "Web Chat",
    time: "18m ago",
    messages: [
      { id: "m1", role: "resident", text: "Do you have any two-bedroom units available for March move-in?" },
      { id: "m2", role: "agent", text: "Hi David! Yes, we have two 2-bedroom units available for March. Unit 415 (2bd/2ba, 1,050 sqft) at $2,200/mo and Unit 601 (2bd/1ba, 900 sqft) at $1,950/mo. Would you like more details on either?" },
    ],
  },
  {
    id: "lc-7",
    resident: "Priya Mehta",
    unit: "Unit 411",
    type: "resident",
    agent: "Maintenance",
    assignee: "ELI+ Maintenance AI",
    property: "Property C",
    channel: "Resident Portal",
    time: "22m ago",
    messages: [
      { id: "m1", role: "resident", text: "The dryer in the laundry room on the 4th floor isn't heating up. It tumbles but clothes come out damp." },
      { id: "m2", role: "agent", text: "Thanks for letting us know, Priya. I'll submit a work order for the 4th floor laundry room dryer right away. We'll have maintenance take a look today." },
    ],
  },
];
